apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
    application.properties: |-
      entur.vehicle-positions.gcp.project.name={{.Values.configMap.projectId}}
      entur.vehicle-positions.gcp.topic.name=protobuf.vehicle_monitoring

      entur.vehicle-positions.gcp.subscription.name=${HOSTNAME}-graphql
      entur.vehicle-positions.gcp.credentials.path={{ .Values.secretMount.mountPath }}

      graphql.servlet.actuator-metrics=true

      graphiql.enabled={{ .Values.configMap.graphiqlEnabled }}
      vehicle.journeyplanner.url={{ .Values.configMap.journeyPlannerUrl }}
      vehicle.journeyplanner.EtClientName={{ .Values.configMap.EtClientName }}

      entur.vehicle-positions.shutdownhook=false
