replicas: ${replicas.RUNNING_REPLICAS}
default_replicas: 4

resources:
  memLimit: 4G
  cpuRequest: '1'
  memRequest: 2G
  xmx: 2G

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0


configMap:
  graphiqlEnabled: false
  topicName: avro.vehicle_monitoring
  journeyPlannerUrl: https://api.entur.io/journey-planner/v3/graphql
  EtClientName: ror.vehicle-positions.graphql
  serviceJourneyLookupEnabled: false
  parallel:
    streamcount: 1
    threadcount: 5

secretMount:
  name: vehicle-positions
  mountPath: /etc/vehicle-positions/credentials.json
  subPath: credentials.json
  secretName: ror-vehicle-positions-sa-key
  readOnly: true


configMapMount:
  name: vehicle-positions-config

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8080

hpa:
  maxReplicas: 20
  minReplicas: 2
  targetCPUUtilizationPercentage: 80