replicas: 1

resources:
  cpuLimit: '3'
  memLimit: 2G
  cpuRequest: '0.5'
  memRequest: 1G
  xmx: 1G

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0


configMap:
  graphiqlEnabled: true

secretMount:
   name: vehicle-positions
   mountPath: /etc/vehicle-positions/credentials.json
   subPath: credentials.json
   secretName: ror-vehicle-positions-sa-key
   readOnly: true


configMapMount:
   name: vehicle-positions-config

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8080

rbac:
  enabled: false