replicas: 1

resources:
  cpuLimit: '5'
  memLimit: 3G
  cpuRequest: '0.5'
  memRequest: 2G
  xmx: 2G

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0


configMap:
  graphiqlEnabled: false
  journeyPlannerUrl: https://api.entur.io/journey-planner/v2/graphql
  EtClientName: ror.vehicle-positions.graphql

secretMount:
   name: vehicle-positions
   mountPath: /etc/vehicle-positions/credentials.json
   subPath: credentials.json
   secretName: ror-vehicle-positions-sa-key
   readOnly: true


configMapMount:
   name: vehicle-positions-config

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8080

rbac:
  enabled: false