apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapMount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
    application.properties: |-
      entur.vehicle-positions.gcp.subscription.project.name={{.Values.configMap.subscriptionProjectId}}
      entur.vehicle-positions.gcp.subscription.name=${HOSTNAME}-graphql
      entur.vehicle-positions.gcp.topic.project.name={{.Values.configMap.topicProjectId}}
      entur.vehicle-positions.gcp.topic.name={{.Values.configMap.topicName}}
      entur.vehicle-positions.gcp.labels={app:'vehicle-positions',team:'ror', slack:'talk-ror', manager:'application'}
      
      # Number of pubsub-streams to open
      entur.vehicle-positions.pubsub.parallel.pullcount={{.Values.configMap.parallel.streamcount}}
      # Number of executor-threads per stream
      entur.vehicle-positions.pubsub.parallel.executorThreadCount={{.Values.configMap.parallel.threadcount}}
    
      entur.vehicle-positions.shutdownhook=false
      entur.default.gcp.credentials.enabled=true

      vehicle.journeyplanner.url={{ .Values.configMap.journeyPlannerUrl }}
      vehicle.journeyplanner.EtClientName={{ .Values.configMap.EtClientName }}
      vehicle.serviceJourney.lookup.enabled={{ .Values.configMap.serviceJourneyLookupEnabled }}
      vehicle.updates.max.validity.minutes=1440
      vehicle.updates.expiry.grace.period=PT10M
      
      vehicle.line.lookup.enabled=true

      vehicle.serviceJourney.concurrent.requests=2
      vehicle.line.concurrent.requests=2

      management.endpoints.web.exposure.include=info, health, prometheus, env, metrics, loggers
      management.endpoints.prometheus.enabled=true
      management.metrics.endpoint.export.prometheus.enabled=true

      # Disabling metrics + tracing, causes excessive memory-usage
      graphql.servlet.actuator-metrics=false
      graphql.servlet.tracing-enabled=false
      
      graphiql.enabled={{ .Values.configMap.graphiqlEnabled }}
      graphiql.static.basePath=/realtime/v1/vehicles/
      graphiql.endpoint.graphql=/realtime/v1/vehicles/graphql
      graphiql.endpoint.subscriptions=/realtime/v1/vehicles/subscriptions
