apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapMount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
    application.properties: |-
      entur.vehicle-positions.gcp.project.name={{.Values.configMap.projectId}}
      entur.vehicle-positions.gcp.topic.name=protobuf.vehicle_monitoring
      entur.vehicle-positions.gcp.subscription.name=${HOSTNAME}-graphql
      entur.vehicle-positions.gcp.labels={app:'vehicle-positions',team:'ror', slack:'talk-ror', manager:'application'}
      entur.vehicle-positions.shutdownhook=false

      vehicle.journeyplanner.url={{ .Values.configMap.journeyPlannerUrl }}
      vehicle.journeyplanner.EtClientName={{ .Values.configMap.EtClientName }}
      vehicle.serviceJourneyCache.enabled={{ .Values.configMap.serviceJourneyCacheEnabled }}
      vehicle.updates.max.validity.minutes=1440
      vehicle.linecache.enabled=true

      management.endpoints.web.exposure.include=info, health, prometheus, env, metrics, loggers
      management.endpoints.prometheus.enabled=true
      management.metrics.endpoint.export.prometheus.enabled=true

      graphql.servlet.actuator-metrics=true
      graphiql.enabled={{ .Values.configMap.graphiqlEnabled }}
      graphiql.static.basePath=/realtime/v1/vehicles/
      graphiql.endpoint.graphql=/realtime/v1/vehicles/graphql
      graphiql.endpoint.subscriptions=/realtime/v1/vehicles/subscriptions
