apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapMount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
    application.properties: |-
      entur.vehicle-positions.gcp.subscription.project.name={{.Values.configMap.subscriptionProjectId}}
      entur.vehicle-positions.gcp.subscription.name=${HOSTNAME}-graphql
      entur.vehicle-positions.gcp.topic.project.name={{.Values.configMap.topicProjectId}}
      entur.vehicle-positions.gcp.topic.name.vm={{.Values.configMap.topicName.vm}}
      entur.vehicle-positions.gcp.topic.name.et={{.Values.configMap.topicName.et}}
      entur.vehicle-positions.gcp.labels={app:'vehicle-positions',team:'ror', slack:'talk-ror', manager:'application'}
      
      # Number of pubsub-streams to open
      entur.vehicle-positions.pubsub.parallel.pullcount={{.Values.configMap.parallel.streamcount}}
      # Number of executor-threads per stream
      entur.vehicle-positions.pubsub.parallel.executorThreadCount={{.Values.configMap.parallel.threadcount}}
    
      entur.vehicle-positions.shutdownhook=false
      entur.default.gcp.credentials.enabled=true

      vehicle.journeyplanner.url={{ .Values.configMap.journeyPlannerUrl }}
      vehicle.journeyplanner.EtClientName={{ .Values.configMap.EtClientName }}
      vehicle.serviceJourney.lookup.enabled={{ .Values.configMap.serviceJourneyLookupEnabled }}
      vehicle.updates.max.validity.minutes=60
      vehicle.updates.expiry.grace.period=PT10M
      
      vehicle.line.lookup.enabled=true
      vehicle.operator.lookup.enabled=true

      vehicle.serviceJourney.concurrent.requests={{ .Values.configMap.journeyplanner.servicejourney.threadpoolsize }}
      vehicle.serviceJourney.concurrent.sleeptime={{ .Values.configMap.journeyplanner.servicejourney.sleeptime }}
      vehicle.line.concurrent.requests={{ .Values.configMap.journeyplanner.line.threadpoolsize }}
      vehicle.line.concurrent.sleeptime={{ .Values.configMap.journeyplanner.line.sleeptime }}

      management.endpoints.web.exposure.include=info, health, prometheus, env, metrics, loggers
      management.endpoints.prometheus.enabled=true
      management.metrics.endpoint.export.prometheus.enabled=true

      # Disabling metrics + tracing, causes excessive memory-usage
      graphql.servlet.actuator-metrics=false
      graphql.servlet.tracing-enabled=false
      
      spring.graphql.graphiql.enabled={{ .Values.configMap.graphiqlEnabled }}
      spring.graphql.websocket.path=/subscriptions
      
      entur.vehicle-positions.client.name.header.name=Et-Client-Name

      entur.vehicle-positions.et.enabled={{ .Values.configMap.etEnabled }}
      entur.vehicle-positions.vm.enabled={{ .Values.configMap.vmEnabled }}
